name: Build and Push to Cachix

on:
  pull_request:
  push:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: -j8 -c6
    - name: nix flake check
      run: nix flake check

  targets:
    name: build and cache
    strategy:
      fail-fast: false
      matrix:
        attr: [circt, circt-ref, circt-const, slang]
    needs: flake-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: -j8 -c6
    - name: Build ${{ matrix.attr }}
      run: nix build -L .#${{ matrix.attr }}
    - name: Run and print version
      run: nix run .#${{ matrix.attr }} -- --version

  devshells:
    runs-on: ubuntu-latest
    needs: flake-check
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: -j8 -c6
    - name: Build "nix develop circt" profile"
      run: nix develop --profile dev-profile
    - name: Build "nix develop circt#git profile"
      run: nix develop .#git --profile dev-profile-git
